default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['BR_DATABASE_USER'] %>
  password: <%= ENV['BR_DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000
  host: <%= ENV['BR_DATABASE_HOST'] %>
development:
  <<: *default
  database: <%= ENV['BR_DATABASE_NAME'] %>
test:
  <<: *default
  database: <%= ENV['BR_DATABASE_NAME_TEST'] %>
production:
  <<: *default
  database: <%= ENV['BR_DATABASE_NAME'] %>